# This workflow will check the code for type and formatting issues

name: Python checking
on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run flake8 check
        run: uvx flake8 src/

      - name: Install dependencies (needed for ty)
        run: uv sync --dev

      - name: Run ty check
        run: uvx ty check --exclude \*.py

